// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.Service.PushNotifications.AutorestClient.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class DataNotificationModel
    {
        /// <summary>
        /// Initializes a new instance of the DataNotificationModel class.
        /// </summary>
        public DataNotificationModel()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the DataNotificationModel class.
        /// </summary>
        /// <param name="type">Possible values include: 'Info', 'KycSucceess',
        /// 'KycRestrictedArea', 'KycNeedToFillDocuments', 'TransctionFailed',
        /// 'TransactionConfirmed', 'AssetsCredited', 'BackupWarning',
        /// 'EthNeedTransactionSign', 'PositionOpened', 'PositionClosed',
        /// 'MarginCall', 'OffchainRequest', 'NeedTransactionSign',
        /// 'PushTxDialog', 'LimitOrderEvent', 'LiveAvailable',
        /// 'ClientDialog'</param>
        public DataNotificationModel(NotificationType type, IList<string> notificationIds = default(IList<string>), string entity = default(string), string id = default(string))
        {
            NotificationIds = notificationIds;
            Type = type;
            Entity = entity;
            Id = id;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "NotificationIds")]
        public IList<string> NotificationIds { get; set; }

        /// <summary>
        /// Gets or sets possible values include: 'Info', 'KycSucceess',
        /// 'KycRestrictedArea', 'KycNeedToFillDocuments', 'TransctionFailed',
        /// 'TransactionConfirmed', 'AssetsCredited', 'BackupWarning',
        /// 'EthNeedTransactionSign', 'PositionOpened', 'PositionClosed',
        /// 'MarginCall', 'OffchainRequest', 'NeedTransactionSign',
        /// 'PushTxDialog', 'LimitOrderEvent', 'LiveAvailable', 'ClientDialog'
        /// </summary>
        [JsonProperty(PropertyName = "Type")]
        public NotificationType Type { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Entity")]
        public string Entity { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Id")]
        public string Id { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="Microsoft.Rest.ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
        }
    }
}
