// Code generated by Microsoft (R) AutoRest Code Generator 1.2.2.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Lykke.Service.PushNotifications.Client.AutorestClient.Models
{
    using Lykke.Service;
    using Lykke.Service.PushNotifications;
    using Lykke.Service.PushNotifications.Client;
    using Lykke.Service.PushNotifications.Client.AutorestClient;
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class DataNotificationModel
    {
        /// <summary>
        /// Initializes a new instance of the DataNotificationModel class.
        /// </summary>
        public DataNotificationModel()
        {
          CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the DataNotificationModel class.
        /// </summary>
        public DataNotificationModel(IList<string> notificationIds = default(IList<string>), string type = default(string), string entity = default(string), string id = default(string))
        {
            NotificationIds = notificationIds;
            Type = type;
            Entity = entity;
            Id = id;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "NotificationIds")]
        public IList<string> NotificationIds { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Type")]
        public string Type { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Entity")]
        public string Entity { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Id")]
        public string Id { get; set; }

    }
}
