// Code generated by Microsoft (R) AutoRest Code Generator 1.2.2.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Lykke.Service.PushNotifications.Client.AutorestClient.Models
{
    using Lykke.Service;
    using Lykke.Service.PushNotifications;
    using Lykke.Service.PushNotifications.Client;
    using Lykke.Service.PushNotifications.Client.AutorestClient;
    using Newtonsoft.Json;
    using System.Linq;

    public partial class RawNotificationModel
    {
        /// <summary>
        /// Initializes a new instance of the RawNotificationModel class.
        /// </summary>
        public RawNotificationModel()
        {
          CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the RawNotificationModel class.
        /// </summary>
        /// <param name="mobileOs">Possible values include: 'Ios',
        /// 'Android'</param>
        public RawNotificationModel(MobileOs mobileOs, string notificationId = default(string), string payload = default(string))
        {
            NotificationId = notificationId;
            Payload = payload;
            MobileOs = mobileOs;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "NotificationId")]
        public string NotificationId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Payload")]
        public string Payload { get; set; }

        /// <summary>
        /// Gets or sets possible values include: 'Ios', 'Android'
        /// </summary>
        [JsonProperty(PropertyName = "MobileOs")]
        public MobileOs MobileOs { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="Microsoft.Rest.ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
        }
    }
}
